## Tableaux
NumPy propose une structure de données populaire, les tableaux (de type array), sur lesquels il est possible d’effectuer de manière efficace des calculs. Les tableaux sont une structure notamment utile pour effectuer des opérations statistiques basiques ainsi que de la génération pseudo-aléatoire de nombres.

La stucture des tableaux ressemble à celle des listes, mais ces dernières sont moins rapides à être traitées et utilisent davantage de mémoire. Le gain de vitesse de traitement des tableaux en NumPy vient du fait que les données sont stockées dans des blocs contigus de mémoire, facilitant ainsi les accès en lecture.

In [1]:
import numpy as np

### Création

La création d’un tableau peut s’effectuer avec la méthode array(), à partir d’une liste, comme nous venon de le faire :

In [2]:
liste = [1,2,4]
tableau = np.array(liste)
print(tableau)
type(tableau)

[1 2 4]


numpy.ndarray

In [3]:
tableau==1

array([ True, False, False])

In [4]:
tableau

array([1, 2, 4])

In [5]:
tableau==2

array([False,  True, False])

In [6]:
s=np.where(tableau==tableau)

In [7]:
tableau==tableau

array([ True,  True,  True])

In [8]:
print(tableau)
s=np.where(tableau==tableau)
print(s)

[1 2 4]
(array([0, 1, 2], dtype=int64),)


In [9]:
print(s)

(array([0, 1, 2], dtype=int64),)


Si on fournit à array() une liste de listes imbriquées de même longueur, un tableau multidimensionnel sera créé :


In [10]:
liste_2 = [ [1,2,3], [4,5,6] ]
tableau_2 = np.array(liste_2)
print(tableau_2)

[[1 2 3]
 [4 5 6]]


Les tableaux peuvent aussi être créés à partir de n-uplets :



In [11]:
nuplet = (1, 2, 3)
tableau = np.array(nuplet)
print(tableau)

[1 2 3]


Un tableau en dimension 1 peut être changé en tableau en dimension 2 (si possible), en modifiant son attribut shape :



In [12]:
tableau = np.array([3, 2, 5, 1, 6, 5])
tableau.shape = (6,1)
print(tableau)

[[3]
 [2]
 [5]
 [1]
 [6]
 [5]]


### Quelques fonctions générant des array


Certaines fonctions de NumPy produisent des tableaux pré-remplis. C’est le cas de la fonction zeros(). Quand on lui fournit une valeur entière n, la fonction zeros() créé un tableau à une dimension, avec n 0 :

In [13]:
print( np.zeros(4) )

[0. 0. 0. 0.]


On peut préciser le type des zéros (par exemple int, int32, int64, float, float32, float64, etc.), à l’aide du paramètre dtype

In [14]:
print( np.zeros(4, dtype = "int") )

[0 0 0 0]


Le type des éléments d’un tableau est indiqué dans l’attribut dtype :



In [15]:
x = np.zeros(4, dtype = "int")
print(x, x.dtype)

[0 0 0 0] int32


Il est par ailleurs possible de convertir le type des éléments dans un un autre type, à l’aide de la méthode astype()

In [16]:
y = x.astype("float")
print(x, x.dtype)

[0 0 0 0] int32


In [17]:
print(y, y.dtype)


[0. 0. 0. 0.] float64


Quand on lui fournit un n-uplet de longueur supérieure à 1, zeros() créé un tableau à plusieurs dimensions :

In [18]:
print( np.zeros((2, 3)) )


[[0. 0. 0.]
 [0. 0. 0.]]


In [19]:
print( np.zeros((2, 3, 4)) )


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


La fonction empty() de Numpy retourne également un tableau sur le même principe que zeros(), mais sans initialiser les valeurs à l’intérieur.

In [20]:
print( np.empty((2, 3), dtype = "int") )


[[0 0 0]
 [0 0 0]]


La fonction ones() de Numpy retourne le même genre de tableaux, avec des 1 en valeurs initialisées :



In [21]:
print( np.ones((2, 3), dtype = "float") )


[[1. 1. 1.]
 [1. 1. 1.]]


Pour choisir une valeur spécifique pour l’initialisation, on peut utiliser la fonction full() de Numpy :



In [22]:
print( np.full((2, 3), 10, dtype = "float") )


[[10. 10. 10.]
 [10. 10. 10.]]


In [23]:
print( np.full((2, 3), np.inf) )


[[inf inf inf]
 [inf inf inf]]


La fonction eye() de Numpy créé un tableau à deux dimensions dans laquelle tous les éléments sont initalisés à zéro, sauf ceux de la diagonale initialisés à 1 :

In [24]:
print( np.eye(2, dtype="int64") )

[[1 0]
 [0 1]]


En modifiant le paramètre mot-clé k, on peut décaler la diagonale :



In [25]:
print( np.eye(3, k=-1) )


[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


La fonction identity() de Numpy créé quant à elle une matrice identité sous la forme d’un tableau :



In [26]:
print( np.identity(3, dtype = "int") )

[[1 0 0]
 [0 1 0]
 [0 0 1]]


La fonction arange() de Numpy permet de générer une séquence de nombres séparés par un interval fixe, le tout stocké dans un tableau. La syntaxe est la suivante :

np.arange( start, stop, step, dtype )
avec start la valeur de départ, stop celle d’arrivée, step le pas, l’espacement entre les nombres de la séquence et dtype le type des nombres :

In [27]:
print( np.arange(5) )


[0 1 2 3 4]


In [28]:
print( np.arange(2, 5) )


[2 3 4]


In [29]:
print( np.arange(2, 10, 2) )


[2 4 6 8]


## Dimensions
Pour connaître la dimension d’un tableau, on peut afficher la valeur de l’attribut ndim :

In [30]:
print("ndim tableau : ", tableau.ndim)

ndim tableau :  2


In [31]:
print("ndim tableau_2 : ", tableau_2.ndim)


ndim tableau_2 :  2


Le nombre d’éléments dans le tableau peut s’obtenir par l’attribut size ou par la fonction size() de Numpy :

In [32]:
print("size tableau : ", tableau.size)

size tableau :  6


In [33]:
print("size tableau_2 : ", tableau_2.size)

size tableau_2 :  6


In [34]:
print("np.size(tableau) :", np.size(tableau))

np.size(tableau) : 6


L’attribut shape retourne un n-uplet indiquant la longueur pour chaque dimension du tableau :


In [35]:
print("size tableau : ", tableau.shape)

size tableau :  (6, 1)


In [36]:
print("size tableau_2 : ", tableau_2.shape)

size tableau_2 :  (2, 3)


### Extraction des éléments d’un tableau
L’accès aux éléments d’un tableau se fait de la même manière que pour les listes. La syntaxe est la suivante :

tableau[lower:upper:step]
avec lower la borne inférieur de la plage d’indices, upper la plage supérieur, et step l’espacement entre les valeurs.

Lorsque lower n’est pas précisé, le premier élément (indicé 0) est considéré comme la valeur attribuée à lower.
Lorsque upper n’est pas précisé, le dernier élément est considéré comme la valeur attribuée à upper.
Lorsque step n’est pas précisé, un pas de 1 est attribué par défaut.
Reprenons rapidement quelques exemples, en s’appuyant sur deux objets : un tableau de dimension 1, et un second de dimension 2.

In [37]:
tableau_1 = np.arange(1,13)
tableau_2 = [ [1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
tableau_2 = np.array(tableau_2)

In [38]:
tableau_1 = np.arange(1,13)

In [39]:
print(tableau_1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [40]:
type(tableau_1)

numpy.ndarray

In [41]:
tableau_1[5]

6

In [42]:
tableau_2.shape

(4, 3)

In [43]:
tableau_2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [44]:
tableau_1[0:4]

array([1, 2, 3, 4])

L’accès au premier élément :

In [45]:
message = "tableau_{}[0] : {} (type : {})"
print(message.format(0, tableau_1[0], type(tableau_1[0])))

tableau_0[0] : 1 (type : <class 'numpy.int32'>)


In [46]:
print(message.format(1, tableau_2[0], type(tableau_2[0])))

tableau_1[0] : [1 2 3] (type : <class 'numpy.ndarray'>)


L’accès aux éléments peut se faire en partant par la fin :


In [47]:
tableau_2[-1]

array([10, 11, 12])

In [48]:
tableau_1[-1]

12

In [49]:
print("tableau_1[-1] : ", tableau_1[-1])
print("tableau_2[-1] : ", tableau_2[-1])


tableau_1[-1] :  12
tableau_2[-1] :  [10 11 12]


In [50]:
tableau_1[2:6]

array([3, 4, 5, 6])

In [51]:
tableau_1==1

array([ True, False, False, False, False, False, False, False, False,
       False, False, False])

In [52]:
tableau_1==tableau_1

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [53]:
print(np.where(tableau_1==tableau_1))

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int64),)


Le découpage est possible :

In [54]:
print("Slice Tableau 1 : \n", tableau_1[2:4])

Slice Tableau 1 : 
 [3 4]


In [55]:
 tableau_2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [101]:
 tableau_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [103]:
 tableau_1.shape=(4,3)

In [108]:
tableau_1.shape

(6, 2)

In [107]:
np.reshape?

In [57]:
tableau_2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [58]:
tableau_2[1:3,:]

array([[4, 5, 6],
       [7, 8, 9]])

In [59]:
print("Scile Tableau 2 : \n", tableau_2[2:4])

Scile Tableau 2 : 
 [[ 7  8  9]
 [10 11 12]]


Pour les tableaux à deux dimensions, on peut accéder aux éléments de la manière suivante, de manière équivalente :


In [60]:
print(tableau_2[2][0])

print(tableau_2[2,0])


7
7


Pour extraire des colonnes d’un tableau à deux entrées :

In [61]:
tableau_2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [62]:
 tableau_2[:, [1]]

array([[ 2],
       [ 5],
       [ 8],
       [11]])

In [63]:
 tableau_2[2:, [1,2]]

array([[ 8,  9],
       [11, 12]])

In [64]:
print("Deuxième colonne : \n", tableau_2[:, [1]])
print("Deuxièmes et troisièmes colonnes : \n", tableau_2[:, [0,2]])

Deuxième colonne : 
 [[ 2]
 [ 5]
 [ 8]
 [11]]
Deuxièmes et troisièmes colonnes : 
 [[ 1  3]
 [ 4  6]
 [ 7  9]
 [10 12]]


#### Extraction à l’aide de booléens

Pour extraire ou non des éléments d’un tableu, on peut utiliser des tableaux de booléens en tant que masques. L’idée est de fournir un tableau de booléens (un masque) de même dimension que celui pour lequel on désire extraire des éléments sous certaines conditions. Lorsque la valeur du booléen dans le masque vaut True, l’élément correspondant du tableau est retourné ; sinon, il ne l’est pas.


In [65]:
tableau = np.array([0, 3, 2, 5, 1, 4])

In [66]:
tableau

array([0, 3, 2, 5, 1, 4])

In [67]:

res = tableau[[True, False, True, False, True, True]]
print(res)

[0 2 1 4]


Seuls les éléments en position 1, 3, 5 et 6 on été retournés.

En pratique, le masque n’est que très rarement créé par l’utilisateur, il est plutôt issu d’une instruction logique appliquée au tableau d’intérêt. Par exemple, dans notre tableau, nous pouvons dans un premier temps créer un masque de manière à identifier les éléments pairs :


In [68]:
masque = tableau % 2 != 0

In [69]:
masque

array([False,  True, False,  True,  True, False])

In [70]:
#masque = tableau % 2 == 0
print(masque)

[False  True False  True  True False]


In [71]:
print(type(masque))

<class 'numpy.ndarray'>


Une fois ce masque créé, on peut l’appliquer au tableau pour extraire uniquement les éléments pour lesquels la valeur correspondante dans le masque vaut True :

In [72]:
print(tableau[masque])

[3 5 1]


### Modification
Pour remplacer les valeurs d’un tableau, on utilise le signe égal (=) :


In [75]:
tableau = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
tableau

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [79]:
tableau[3]=10

In [80]:
#tableau[0] = 10
print(tableau)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 10 10]]


Si on fournit un scalaire lors du remplacement, la valeur sera répétée pour tous les éléments de la dimension :

In [81]:
tableau[0] = 100
print(tableau)

[[100 100 100]
 [  4   5   6]
 [  7   8   9]
 [ 10  10  10]]


Idem avec un découpage :

In [88]:
tableau[0:2]

array([[100, 100, 100],
       [  4,   5,   6]])

In [82]:
tableau[0:2] = 300
print(tableau)

[[300 300 300]
 [300 300 300]
 [  7   8   9]
 [ 10  10  10]]


D’ailleurs, un découpage avec juste les deux points sans préciser les paramètres de début et de fin du découpage suivi d’un signe égal et d’un nombre remplace toutes les valeurs du tableau par ce nombre :


In [83]:
tableau[:] = 1
print(tableau)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


### Ajout d’éléments
Pour ajouter des éléments, on utilise la fonction append() de NumPy. Il faut noter que l’appel à cette fonction ne modifie pas l’objet auquel on ajoute les valeurs. Si on désire que les modifications sont apportées à cet objet, il faut l’écraser :


In [91]:
t_1 = np.array([1,3,5])
print("t_1 : ", t_1)
## t_1 :  [1 3 5]
t_1 = np.append(t_1, 1)
print("t_1 après l'ajout : ", t_1)

t_1 :  [1 3 5]
t_1 après l'ajout :  [1 3 5 1]


In [84]:
np.append?

In [85]:
t_1 = np.array([1,3,5])

In [88]:
t_1

array([1, 3, 5])

In [89]:
t_1 = np.append(t_1,15)

In [98]:
t_1.shape

(4,)

Pour ajouter une colonne à un tableau à deux dimensions :

In [113]:
t_2 = np.array([[1,2,3], [5,6,7]])

In [114]:
t_2

array([[1, 2, 3],
       [5, 6, 7]])

In [116]:
ajout_col_t_2 = np.array([[4], [8]])

In [117]:
ajout_col_t_2

array([[4],
       [8]])

In [118]:
t_2 = np.append(t_2,ajout_col_t_2, axis = 1)

In [120]:
t_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [121]:
t_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [122]:
x=np.array([1,2,3,4,5,6])

In [123]:
t_2 = np.array([[1,2,3], [5,6,7]])
print("t_2 : \n", t_2)

ajout_col_t_2 = np.array([[4], [8]])
t_2 = np.append(t_2,ajout_col_t_2, axis = 1)
print("t_2 après ajout colonne : \n", t_2)

t_2 : 
 [[1 2 3]
 [5 6 7]]
t_2 après ajout colonne : 
 [[1 2 3 4]
 [5 6 7 8]]


Pour ajouter une ligne, on utilise la fonction vstack() de Numpy :

In [125]:
np.vstack??

In [127]:
ajout_ligne_t_2 = np.array([10, 11, 12,54])
t_2 = np.vstack([t_2,ajout_ligne_t_2])
print("t_2 après ajout ligne : \n", t_2)

t_2 après ajout ligne : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [10 11 12 54]
 [10 11 12 54]]


#### Suppression d’éléments

Pour supprimer des éléments, on utilise la fonction delete() de NumPy :

In [134]:
print("t_1 : ", t_1)

t_1 :  [ 3 15]


In [131]:
np.delete(t_1, (-1))

array([1, 3, 5])

In [135]:
x=np.array([1,2,3,4,5,6])

In [136]:
np.delete(x, ([1,3]))

array([1, 3, 5, 6])

Note : pour que la suppression soit effective, on assigne le résultat de np.delete() à l’objet.

Pour supprimer plusieurs éléments :

In [132]:
print("t_1 : ", t_1)

t_1 :  [ 1  3  5 15]


In [133]:
t_1 = np.delete(t_1, ([0, 2]))
print(t_1)

[ 3 15]


Pour supprimer une colonne d’un tableau à deux dimensions :


In [148]:
print("t_2 : ", t_2)


t_2 :  [[ 1  2  3  4]
 [ 5  6  7  8]
 [10 11 12 54]]


In [137]:
np.delete(t_2, (1), axis=1)

array([[ 1,  3,  4],
       [ 5,  7,  8],
       [10, 12, 54],
       [10, 12, 54]])

Supprimer plusieurs colonnes :

In [139]:
print("t_2 : ", t_2)

np.delete(t_2, ([0,2]), axis=1)

t_2 :  [[ 1  2  3  4]
 [ 5  6  7  8]
 [10 11 12 54]
 [10 11 12 54]]


array([[ 2,  4],
       [ 6,  8],
       [11, 54],
       [11, 54]])

Et pour supprimer une ligne :

In [140]:
print("t_2 : ", t_2)
np.delete(t_2, (0), axis=0)


t_2 :  [[ 1  2  3  4]
 [ 5  6  7  8]
 [10 11 12 54]
 [10 11 12 54]]


array([[ 5,  6,  7,  8],
       [10, 11, 12, 54],
       [10, 11, 12, 54]])

Supprimer plusieurs lignes :


In [142]:
print("t_2 : ", t_2)
np.delete(t_2, ([0,2]), axis=0)

t_2 :  [[ 1  2  3  4]
 [ 5  6  7  8]
 [10 11 12 54]
 [10 11 12 54]]


array([[ 5,  6,  7,  8],
       [10, 11, 12, 54]])

In [167]:
tableau_1 = np.array([1, 2, 3])
tableau_1

array([1, 2, 3])

In [168]:
tableau_2 = np.array(tableau_1)

In [169]:
tableau_2

array([1, 2, 3])

In [170]:
tableau_1[1]=10000

In [171]:
tableau_1

array([    1, 10000,     3])

In [172]:
tableau_2

array([1, 2, 3])

In [152]:
tableau_1

array([0, 1, 2])

In [154]:
tableau_2

array([1, 2, 3])

In [156]:
tableau_2-5

array([-4, -3, -2])

In [157]:
tableau_1

array([0, 1, 2])

### Copie de tableau

In [165]:
tableau_1 = np.array([1, 2, 3])
tableau_2 = tableau_1

Modifions le premier élément de tableau_2, et observons le contenu de tableau_2 et de tableau_1 :

In [173]:
tableau_2[0] = 0
print("Tableau 1 : \n", tableau_1)

print("Tableau 2 : \n", tableau_2)

Tableau 1 : 
 [    1 10000     3]
Tableau 2 : 
 [0 2 3]


Comme on peut le constater, le fait d’avoir utilisé le signe égal a simplement créé une référence et non pas une copie.

Pour effectuer une copie de tableaux, plusieurs façons existent. Parmi elles, l’utilisation de la fonction np.array() :

In [174]:
tableau_1 = np.array([1, 2, 3])
tableau_2 = np.array(tableau_1)
tableau_2[0] = 0
print("tableau_1 : ", tableau_1)
print("tableau_2 : ", tableau_2)

tableau_1 :  [1 2 3]
tableau_2 :  [0 2 3]


On peut également utiliser la méthode copy() :

In [175]:
tableau_1 = np.array([1, 2, 3])
tableau_2 = tableau_1.copy()
tableau_2[0] = 0
print("tableau_1 : ", tableau_1)
print("tableau_2 : ", tableau_2)

tableau_1 :  [1 2 3]
tableau_2 :  [0 2 3]


On peut noter que lorsque l’on fait un découpement, un nouvel objet est créé, pas une référence :

In [176]:
tableau_1 = np.array([1, 2, 3, 4])
tableau_2 = tableau_1[:2]
tableau_2[0] = 0
print("tableau_1 : ", tableau_1)
print("tableau_2 : ", tableau_2)

tableau_1 :  [0 2 3 4]
tableau_2 :  [0 2]


### Tri

La librairie NumPy fournit une fonction pour trier les tableaux : sort().


In [178]:
tableau = np.array([3, 2, 5, 1, 6, 5])
print("Tableau trié : ", np.sort(tableau))
print("Tableau : ", tableau)

Tableau trié :  [1 2 3 5 5 6]
Tableau :  [3 2 5 1 6 5]


Comme on peut le constater, la fonction sort() de NumPy propose une vue : le tableau n’est pas modifié, ce qui n’est pas le cas si on utilise la méthode sort() :


In [180]:
tableau = np.array([3, 2, 5, 1, 6, 5])
tableau.sort()
print("Le tableau a été modifié : ", tableau)

Le tableau a été modifié :  [1 2 3 5 5 6]


### Transposition

Pour obtenir la transposée d’un tableau, on fait appel à l’attribut T. Il faut noter que l’on obtient une vue de l’objet, que cela ne le modifie pas.

In [184]:
tableau = np.array([3, 2, 5, 1, 6, 5])
tableau.shape = (3,2)
print("Tableau : \n", tableau)
#print("Tableau transposé : \n", tableau.T)

Tableau : 
 [[3 2]
 [5 1]
 [6 5]]


In [186]:
tableau.shape

(3, 2)

In [190]:
tableau.T

array([[3, 5, 6],
       [2, 1, 5]])

On peut également utiliser la fonction transpose() de NumPy :


In [191]:
print(np.transpose(tableau))

[[3 5 6]
 [2 1 5]]


**Attention**, si on assigne un nom à la transposée, que ce soit en utilisant l’attribut T ou la méthode np.transpose(), cela créé une référence, pas une copie d’élément…


In [192]:
tableau_transpose = np.transpose(tableau)
tableau_transpose[0,0] = 99
print("tableau : \n", tableau)
print("tableau_transpose : \n", tableau_transpose)

tableau : 
 [[99  2]
 [ 5  1]
 [ 6  5]]
tableau_transpose : 
 [[99  5  6]
 [ 2  1  5]]


Pour savoir si un tableau est une vue ou non, on peut afficher l’attribut base, qui retourne None si ce n’est pas le cas :


In [194]:
print("tableau : ", tableau.base)
print("tableau_transpose : ", tableau_transpose.base)

tableau :  None
tableau_transpose :  [[99  2]
 [ 5  1]
 [ 6  5]]


### Opérations sur les tableaux
Il est possible d’utiliser des opérateurs sur les tableaux. Leur effet nécessite quelques explications.

#### Opérateurs + et -
Lorsque l’opérateur + (-) est utilisé entre deux tableaux de même dimension, une addition (soustraction) terme à terme est effectuée :

In [195]:
t_1 = np.array([1, 2, 3, 4])
t_2 = np.array([5, 6, 7, 8])
t_3 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
t_4 = np.array([[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]])
t_1 + t_2
t_3 + t_4
t_1 - t_2

array([-4, -4, -4, -4])

Lorsque l’opérateur + (-) est utilisé entre un scalaire et un tableau, le scalaire est ajouté (soustrait) à tous les éléments du tableau :


In [196]:
print("t_1 + 3 : \n", t_1 + 3)
print("t_1 + 3. : \n", t_1 + 3.)
print("t_3 + 3 : \n", t_3 + 3)
print("t_3 - 3 : \n", t_3 - 3)

t_1 + 3 : 
 [4 5 6 7]
t_1 + 3. : 
 [4. 5. 6. 7.]
t_3 + 3 : 
 [[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
t_3 - 3 : 
 [[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]]


#### Opérateurs * et /

Lorsque l’opérateur * (/) est utilisé entre deux tableaux de même dimension, une multiplication (division) terme à terme est effectuée :

In [197]:
t_1 * t_2
t_3 * t_4
t_3 / t_4

array([[0.07692308, 0.14285714, 0.2       , 0.25      ],
       [0.29411765, 0.33333333, 0.36842105, 0.4       ],
       [0.42857143, 0.45454545, 0.47826087, 0.5       ]])

Lorsque l’opérateur * (/) est utilisé entre un scalaire et un tableau, tous les éléments du tableau sont multipliés (divisés) par ce scalaire :


In [198]:
print("t_1 * 3 : \n", t_1 * 3)
print("t_1 / 3 : \n", t_1 / 3)

t_1 * 3 : 
 [ 3  6  9 12]
t_1 / 3 : 
 [0.33333333 0.66666667 1.         1.33333333]


#### Puissance

Il est également possible d’élever chaque nombre d’un tableau à une puissance donnée :

In [199]:
print("t_1 ** 3 : \n", t_1 ** 3)

t_1 ** 3 : 
 [ 1  8 27 64]


#### Opérations sur des matrices

<center> <a><img src = "produit matricielle.gif" width = 400, align = "center"></a> </center>

En plus des opérations/soustraction/multiplication/division terme à terme ou par un scalaire, il est possible d’effectuer certains calculs sur des tableaux à deux dimension.

Pour effectuer un produit matriciel, NumPy fournit la fonction dot() :

In [200]:
np.dot(t_3, t_4.T)

array([[150, 190, 230],
       [382, 486, 590],
       [614, 782, 950]])

Le produit matriciel peut également s’obtenir à l’aide de l’opérateur @ :

In [201]:
t_3 @ t_4.T

array([[150, 190, 230],
       [382, 486, 590],
       [614, 782, 950]])

Le produit d’un vecteur avec une matrice est également possible :

In [202]:
np.dot(t_1, t_3.T)

array([ 30,  70, 110])

### Méthodes et fonctions mathématiques et statistiques

NumPy fournit de nombreuses méthodes pour calculer des statistiques sur l’ensemble des valeurs des tableaux, ou sur un des axes des tableaux (par exemple sur l’équivalent de lignes ou des colonnes dans les tableaux à deux dimensions).

In [203]:
arr = 10 * np.random.randn(2,5)
print(arr)

[[-27.35221405  -2.19009416  -3.44228341  11.69751138 -29.92143672]
 [ 14.97824992  -9.71740811   8.93402988  -1.81113998   3.20927182]]


Calcul de la moyenne pour tous les éléments

In [204]:
print(arr.mean())

-3.56155134278646


Moyenne par ligne

In [205]:
print(arr.mean(axis = 1))

[-10.24170339   3.11860071]


Moyenne par colonne

In [181]:
print(arr.mean(axis = 0))

[ -5.66542393   6.13091365  -5.91641524 -20.07960609 -14.29980561]


Somme des éléments

In [182]:
print(arr.sum())

-79.66067446174742


Médiane

In [183]:
print(np.median(arr, axis = 1))

[-19.18406075  -5.87999909]


# Exercice d'application

Considérons le vecteur suivant :  
x=[1 2 3 4 5 ]
 
* Créer ce vecteur à l’aide d’un tableau que l’on appellera x.
* Afficher le type de x puis sa longueur.
* Extraire le premier élément, puis en faire de même avec le dernier.
* Extraire les trois premiers éléments et les stocker dans un vecteur que l’on nommera a.
* Extraire les 1er, 2e et 5e éléments du vecteur (attention aux positions) ; les stocker dans un vecteur que l’on nommera b.
* Additionner le nombre 10 au vecteur x, puis multiplier le résultat par 2.
* Effectuer l’addition de a et b, commenter le résultat.
* Effectuer l’addition suivante : x+a ; commenter le résultat, puis regarder le résultat de a+x.
* Multiplier le vecteur par le scalaire c que l’on fixera à 2.
* Effectuer la multiplication de a et b ; commenter le résultat.
* Effectier la multiplication suivante : x*a ; commenter le résultats.
* Récupérer les positions des multiples de 2 et les stocker dans un vecteur que l’on nommera ind, piuis conserver uniquement les multiples de 2 de x dans un vecteur que l’on nommera mult_2.
* Afficher les éléments de x qui sont multiples de 3 et multiples de 2.
* Afficher les éléments de x qui sont multiples de 3 ou multiples de 2.
* Calculer la somme des éléments de x.
* Remplacer le premier élément de x par un 4.
* Remplacer le premier élément de x par la valeur NaN, puis calculer la somme des éléments de x. 18 Supprimer le vecteur x.